package com.raulbarca.portfolio.core.network.ktor

import com.raulbarca.portfolio.BuildConfig
import com.raulbarca.portfolio.core.localization.locale.CurrentAppLocale
import com.raulbarca.portfolio.core.model.PortfolioData
import com.raulbarca.portfolio.core.model.ResumeData
import com.raulbarca.portfolio.core.network.PortfolioNetworkDataSource
import io.ktor.client.HttpClient
import kotlinx.serialization.json.Json

const val API_HOST = BuildConfig.API_HOST

class KtorPortfolioNetwork(
    private val client: HttpClient,
) : PortfolioNetworkDataSource {

    override suspend fun getPortfolioOverview(): PortfolioData {
        return json.decodeFromString<PortfolioData>(overviewJson[CurrentAppLocale.isoFormat].orEmpty())
//        Here we are returning dummy data, but if you have created an API for this code,
//        you can call it to get [PortfolioData] response:
//        return client.get("$API_HOST/overview").body<PortfolioData>()
    }

    override suspend fun getResume(): ResumeData {
        return json.decodeFromString<ResumeData>(resumeJson[CurrentAppLocale.isoFormat].orEmpty())
//        Here we are returning dummy data, but if you have created an API for this code,
//        you can call it to get [PortfolioData] response:
//        return client.get("$API_HOST/resume").body<ResumeData>()
    }

    companion object {
        private val json = Json { ignoreUnknownKeys = true }
        private val overviewJson = mapOf(
            "en" to "{\"projects\":[{\"description\":\"Corporate Health and well-being app\",\"links\":[{\"image\":\"GooglePlay\",\"contentDescription\":\"Google Play\",\"url\":\"https://play.google.com/store/apps/details?id=com.cgi.android.oxygen\"}],\"title\":\"CGI Oxygen\"},{\"description\":\"Digital banking app\",\"links\":[{\"image\":\"GooglePlay\",\"contentDescription\":\"Google Play\",\"url\":\"https://play.google.com/store/apps/details?id=com.itau.iti\"}],\"title\":\"iti\"}],\"greeting\":\"Hey, I'm Raul\",\"avatarImageUrl\":\"https://avatars.githubusercontent.com/u/50126493\",\"roles\":[{\"description\":\"I create modern Android apps using Kotlin and Jetpack Compose.\",\"title\":\"Android App Development\"},{\"description\":\"I create responsive multiplatform apps and websites with Compose Multiplatform.\",\"title\":\"Multiplatform Development\"},{\"description\":\"Design projects thinking of WCAG principles.\",\"title\":\"Accessibility\"}],\"contactUrl\":\"https://www.linkedin.com/in/raul-barca-522a16a0\",\"id\":\"en\",\"headline\":\"A Software Engineer creating the best user experience on mobile apps\",\"aboutMe\":\"I’m an Android Developer with a strong foundation in Kotlin, Jetpack Compose, and accessibility.\\nSince late 2019, I’ve worked as a full-time Android developer, and I’ve been freelancing in this field since early 2018.\\nMy journey in IT began in 2012, covering diverse domains like finance, energy, banking, and well-being.\\nI’m passionate about building user-centered mobile applications that are both high-quality and accessible.\\n\\nBeyond my professional work, I volunteer in STEM programs, introducing young students to programming and robotics,\\nas I believe in the power of tech education and giving back to the community.\"}",
            "fr" to "{\"projects\":[{\"description\":\"Application de santé et de bien-être corporatif\",\"links\":[{\"image\":\"GooglePlay\",\"contentDescription\":\"Google Play\",\"url\":\"https://play.google.com/store/apps/details?id=com.cgi.android.oxygen\"}],\"title\":\"CGI Oxygen\"},{\"description\":\"Application bancaire numérique\",\"links\":[{\"image\":\"GooglePlay\",\"contentDescription\":\"Google Play\",\"url\":\"https://play.google.com/store/apps/details?id=com.itau.iti\"}],\"title\":\"iti\"}],\"greeting\":\"Salut, je suis Raul\",\"avatarImageUrl\":\"https://avatars.githubusercontent.com/u/50126493\",\"roles\":[{\"description\":\"Je crée des applications Android modernes en utilisant Kotlin et Jetpack Compose.\",\"title\":\"Développement d'applications Android\"},{\"description\":\"Je crée des applications et des sites Web multiplateformes réactifs avec Compose Multiplatform.\",\"title\":\"Développement multiplateforme\"},{\"description\":\"Conception de projets en tenant compte des principes WCAG.\",\"title\":\"Accessibilité\"}],\"contactUrl\":\"https://www.linkedin.com/in/raul-barca-522a16a0\",\"id\":\"fr\",\"headline\":\"Un ingénieur logiciel qui crée la meilleure expérience utilisateur sur les applications mobiles\",\"aboutMe\":\"Je suis un développeur Android avec une solide base en Kotlin, Jetpack Compose et accessibilité.\\nDepuis la fin 2019, je travaille comme développeur Android à temps plein, et je suis travailleur autonome dans ce domaine depuis le début 2018.\\nMon parcours en TI a débuté en 2012, couvrant divers domaines comme la finance, l'énergie, les services bancaires et le bien-être.\\nJe suis passionné par la création d'applications mobiles centrées sur l'utilisateur qui sont à la fois de haute qualité et accessibles.\\n\\nAu-delà de mon travail professionnel, je fais du bénévolat dans des programmes STIM, initiant les jeunes étudiants à la programmation et à la robotique,\\ncar je crois au pouvoir de l'éducation technologique et à l'importance de redonner à la communauté.\"}",
            "pt" to "{\"projects\":[{\"description\":\"Aplicativo corporativo de saúde e bem-estar\",\"links\":[{\"image\":\"GooglePlay\",\"contentDescription\":\"Google Play\",\"url\":\"https://play.google.com/store/apps/details?id=com.cgi.android.oxygen\"}],\"title\":\"CGI Oxygen\"},{\"description\":\"Aplicativo de banco digital\",\"links\":[{\"image\":\"GooglePlay\",\"contentDescription\":\"Google Play\",\"url\":\"https://play.google.com/store/apps/details?id=com.itau.iti\"}],\"title\":\"iti\"}],\"greeting\":\"Olá, eu sou o Raul\",\"avatarImageUrl\":\"https://avatars.githubusercontent.com/u/50126493\",\"roles\":[{\"description\":\"Crio aplicativos Android modernos usando Kotlin e Jetpack Compose.\",\"title\":\"Desenvolvimento de Apps Android\"},{\"description\":\"Crio aplicativos e sites multiplataforma responsivos com Compose Multiplatform.\",\"title\":\"Desenvolvimento Multiplataforma\"},{\"description\":\"Projetos desenvolvidos pensando nos princípios WCAG.\",\"title\":\"Acessibilidade\"}],\"contactUrl\":\"https://www.linkedin.com/in/raul-barca-522a16a0\",\"id\":\"pt\",\"headline\":\"Um Engenheiro de Software criando a melhor experiência do usuário em aplicativos móveis\",\"aboutMe\":\"Sou um Desenvolvedor Android com uma base sólida em Kotlin, Jetpack Compose e acessibilidade.\\nDesde o final de 2019, trabalho como desenvolvedor Android em tempo integral, e atuo como freelancer nesta área desde o início de 2018.\\nMinha jornada em TI começou em 2012, abrangendo diversos domínios como finanças, energia, bancário e bem-estar.\\nSou apaixonado por criar aplicativos móveis centrados no usuário que são tanto de alta qualidade quanto acessíveis.\\n\\nAlém do meu trabalho profissional, sou voluntário em programas STEM, introduzindo jovens estudantes à programação e robótica,\\npois acredito no poder da educação tecnológica e em retribuir à comunidade.\"}",
        )
        private val resumeJson = mapOf(
            "en" to "{\"education\":[{\"imageUrl\":\"https://media.licdn.com/dms/image/v2/D4D0BAQE92sjYGQ9eqQ/company-logo_100_100/company-logo_100_100/0/1728258542573/faculdade_senai_fatesg_logo?e=1739404800&v=beta&t=0s_j-jxfT7J4QEigUMlZEKzABJ3iFHxb_F1RpE_Kvkw\",\"institutionName\":\"SENAI Fatesg\",\"start\":\"2014\",\"institutionUrl\":\"https://senaigoias.com.br/faculdade-fatesg\",\"location\":\"Goiânia, Goiás, Brazil\",\"end\":\"2016\",\"title\":\"Software Project and Development for Mobile Devices\"},{\"imageUrl\":\"https://media.licdn.com/dms/image/v2/C4D0BAQEfBMvGBE7yZg/company-logo_100_100/company-logo_100_100/0/1630536419962/universidade_federal_de_goias_logo?e=1739404800&v=beta&t=6uSvS264zp-8-41SKe4KgmS8S-nA_M9lhjqiHsK5LEs\",\"institutionName\":\"Universidade Federal de Goiás\",\"start\":\"2010\",\"institutionUrl\":\"https://ufg.br\",\"location\":\"Goiânia, Goiás, Brazil\",\"end\":\"2014\",\"title\":\"Software Engineering\"}],\"id\":\"en\",\"experience\":[{\"imageUrl\":\"https://media.licdn.com/dms/image/v2/C4E0BAQErzXWSFkn9tQ/company-logo_100_100/company-logo_100_100/0/1663664110809/cgi_logo?e=1739404800&v=beta&t=9SKGkVBifCIIjdGOeOViiVBhfn4MGYXmY74iF4b5wP8\",\"companyName\":\"CGI\",\"start\":\"Sep 2021\",\"location\":\"Sherbrooke, Québec, Canada\",\"end\":\"now\",\"companyUrl\":\"https://www.cgi.com/en\",\"title\":\"Android Developer\"},{\"imageUrl\":\"https://media.licdn.com/dms/image/v2/D4D0BAQGwhrn49xXUiw/company-logo_100_100/company-logo_100_100/0/1684433959108/zupinnovation_logo?e=1739404800&v=beta&t=UtXHdL8VJyt_nzz6_oZ1nZ-Qa7fLOcXPSvS2S3Sf-iw\",\"companyName\":\"Zup Innovation\",\"start\":\"Dec 2019\",\"location\":\"Campinas, São Paulo, Brazil\",\"end\":\"Jul 2021\",\"companyUrl\":\"https://zupinnovation.com\",\"title\":\"Android Developer\"},{\"imageUrl\":\"https://media.licdn.com/dms/image/v2/C4E0BAQHbAWs02xP3ww/company-logo_100_100/company-logo_100_100/0/1630602647189/enel_brasil_logo?e=1739404800&v=beta&t=Zb4jEg6e9KIWQNhp2d5QmLeYkYm9mSSd0rgpGTdDp4o\",\"companyName\":\"Enel\",\"start\":\"Mar 2015\",\"location\":\"Goiânia, Goiás, Brazil\",\"end\":\"Dec 2019\",\"companyUrl\":\"https://www.enel.com.br\",\"title\":\"Systems Analyst\"},{\"imageUrl\":\"https://media.licdn.com/dms/image/v2/D4D0BAQGw3BVYHzaBwQ/company-logo_100_100/company-logo_100_100/0/1720207931733/decisaosistemas_logo?e=1739404800&v=beta&t=uMMpXkUBBFuspkIU_SsNqi-RLZ2JDh74-NS5m0ygvfc\",\"companyName\":\"Decisão Sistemas\",\"start\":\"Oct 2012\",\"location\":\"Aparecida de Goiânia, Goiás, Brazil\",\"end\":\"Feb 2015\",\"companyUrl\":\"https://decisaosistemas.com.br/\",\"title\":\"Tests Analyst\"}]}",
            "fr" to "{\"education\":[{\"imageUrl\":\"https://media.licdn.com/dms/image/v2/D4D0BAQE92sjYGQ9eqQ/company-logo_100_100/company-logo_100_100/0/1728258542573/faculdade_senai_fatesg_logo?e=1739404800&v=beta&t=0s_j-jxfT7J4QEigUMlZEKzABJ3iFHxb_F1RpE_Kvkw\",\"institutionName\":\"SENAI Fatesg\",\"start\":\"2014\",\"institutionUrl\":\"https://senaigoias.com.br/faculdade-fatesg\",\"location\":\"Goiânia, Goiás, Brésil\",\"end\":\"2016\",\"title\":\"Projet et développement de logiciels pour appareils mobiles\"},{\"imageUrl\":\"https://media.licdn.com/dms/image/v2/C4D0BAQEfBMvGBE7yZg/company-logo_100_100/company-logo_100_100/0/1630536419962/universidade_federal_de_goias_logo?e=1739404800&v=beta&t=6uSvS264zp-8-41SKe4KgmS8S-nA_M9lhjqiHsK5LEs\",\"institutionName\":\"Universidade Federal de Goiás\",\"start\":\"2010\",\"institutionUrl\":\"https://ufg.br\",\"location\":\"Goiânia, Goiás, Brésil\",\"end\":\"2014\",\"title\":\"Génie logiciel\"}],\"id\":\"fr\",\"experience\":[{\"imageUrl\":\"https://media.licdn.com/dms/image/v2/C4E0BAQErzXWSFkn9tQ/company-logo_100_100/company-logo_100_100/0/1663664110809/cgi_logo?e=1739404800&v=beta&t=9SKGkVBifCIIjdGOeOViiVBhfn4MGYXmY74iF4b5wP8\",\"companyName\":\"CGI\",\"start\":\"Sept. 2021\",\"location\":\"Sherbrooke, Québec, Canada\",\"end\":\"maintenant\",\"companyUrl\":\"https://www.cgi.com/en\",\"title\":\"Développeur Android\"},{\"imageUrl\":\"https://media.licdn.com/dms/image/v2/D4D0BAQGwhrn49xXUiw/company-logo_100_100/company-logo_100_100/0/1684433959108/zupinnovation_logo?e=1739404800&v=beta&t=UtXHdL8VJyt_nzz6_oZ1nZ-Qa7fLOcXPSvS2S3Sf-iw\",\"companyName\":\"Zup Innovation\",\"start\":\"Déc. 2019\",\"location\":\"Campinas, São Paulo, Brésil\",\"end\":\"Juil. 2021\",\"companyUrl\":\"https://zupinnovation.com\",\"title\":\"Développeur Android\"},{\"imageUrl\":\"https://media.licdn.com/dms/image/v2/C4E0BAQHbAWs02xP3ww/company-logo_100_100/company-logo_100_100/0/1630602647189/enel_brasil_logo?e=1739404800&v=beta&t=Zb4jEg6e9KIWQNhp2d5QmLeYkYm9mSSd0rgpGTdDp4o\",\"companyName\":\"Enel\",\"start\":\"Mars 2015\",\"location\":\"Goiânia, Goiás, Brésil\",\"end\":\"Déc. 2019\",\"companyUrl\":\"https://www.enel.com.br\",\"title\":\"Analyste de systèmes\"},{\"imageUrl\":\"https://media.licdn.com/dms/image/v2/D4D0BAQGw3BVYHzaBwQ/company-logo_100_100/company-logo_100_100/0/1720207931733/decisaosistemas_logo?e=1739404800&v=beta&t=uMMpXkUBBFuspkIU_SsNqi-RLZ2JDh74-NS5m0ygvfc\",\"companyName\":\"Decisão Sistemas\",\"start\":\"Oct. 2012\",\"location\":\"Aparecida de Goiânia, Goiás, Brésil\",\"end\":\"Févr. 2015\",\"companyUrl\":\"https://decisaosistemas.com.br/\",\"title\":\"Analyste de tests\"}]}",
            "pt" to "{\"education\":[{\"imageUrl\":\"https://media.licdn.com/dms/image/v2/D4D0BAQE92sjYGQ9eqQ/company-logo_100_100/company-logo_100_100/0/1728258542573/faculdade_senai_fatesg_logo?e=1739404800&v=beta&t=0s_j-jxfT7J4QEigUMlZEKzABJ3iFHxb_F1RpE_Kvkw\",\"institutionName\":\"SENAI Fatesg\",\"start\":\"2014\",\"institutionUrl\":\"https://senaigoias.com.br/faculdade-fatesg\",\"location\":\"Goiânia, Goiás, Brasil\",\"end\":\"2016\",\"title\":\"Projeto e Desenvolvimento de Software para Dispositivos Móveis\"},{\"imageUrl\":\"https://media.licdn.com/dms/image/v2/C4D0BAQEfBMvGBE7yZg/company-logo_100_100/company-logo_100_100/0/1630536419962/universidade_federal_de_goias_logo?e=1739404800&v=beta&t=6uSvS264zp-8-41SKe4KgmS8S-nA_M9lhjqiHsK5LEs\",\"institutionName\":\"Universidade Federal de Goiás\",\"start\":\"2010\",\"institutionUrl\":\"https://ufg.br\",\"location\":\"Goiânia, Goiás, Brasil\",\"end\":\"2014\",\"title\":\"Engenharia de Software\"}],\"id\":\"pt\",\"experience\":[{\"imageUrl\":\"https://media.licdn.com/dms/image/v2/C4E0BAQErzXWSFkn9tQ/company-logo_100_100/company-logo_100_100/0/1663664110809/cgi_logo?e=1739404800&v=beta&t=9SKGkVBifCIIjdGOeOViiVBhfn4MGYXmY74iF4b5wP8\",\"companyName\":\"CGI\",\"start\":\"Set 2021\",\"location\":\"Sherbrooke, Quebec, Canadá\",\"end\":\"atual\",\"companyUrl\":\"https://www.cgi.com/en\",\"title\":\"Desenvolvedor Android\"},{\"imageUrl\":\"https://media.licdn.com/dms/image/v2/D4D0BAQGwhrn49xXUiw/company-logo_100_100/company-logo_100_100/0/1684433959108/zupinnovation_logo?e=1739404800&v=beta&t=UtXHdL8VJyt_nzz6_oZ1nZ-Qa7fLOcXPSvS2S3Sf-iw\",\"companyName\":\"Zup Innovation\",\"start\":\"Dez 2019\",\"location\":\"Campinas, São Paulo, Brasil\",\"end\":\"Jul 2021\",\"companyUrl\":\"https://zupinnovation.com\",\"title\":\"Desenvolvedor Android\"},{\"imageUrl\":\"https://media.licdn.com/dms/image/v2/C4E0BAQHbAWs02xP3ww/company-logo_100_100/company-logo_100_100/0/1630602647189/enel_brasil_logo?e=1739404800&v=beta&t=Zb4jEg6e9KIWQNhp2d5QmLeYkYm9mSSd0rgpGTdDp4o\",\"companyName\":\"Enel\",\"start\":\"Mar 2015\",\"location\":\"Goiânia, Goiás, Brasil\",\"end\":\"Dez 2019\",\"companyUrl\":\"https://www.enel.com.br\",\"title\":\"Analista de Sistemas\"},{\"imageUrl\":\"https://media.licdn.com/dms/image/v2/D4D0BAQGw3BVYHzaBwQ/company-logo_100_100/company-logo_100_100/0/1720207931733/decisaosistemas_logo?e=1739404800&v=beta&t=uMMpXkUBBFuspkIU_SsNqi-RLZ2JDh74-NS5m0ygvfc\",\"companyName\":\"Decisão Sistemas\",\"start\":\"Out 2012\",\"location\":\"Aparecida de Goiânia, Goiás, Brasil\",\"end\":\"Fev 2015\",\"companyUrl\":\"https://decisaosistemas.com.br/\",\"title\":\"Analista de Testes\"}]}",
        )
    }
}